### ISSUE TITLE
在脚本里加上项目地址

### ISSUE THREAD

**Issue by TCOTC** [zxkmm/ld246_blacklist#3]

**Comment by zxkmm** [comment]
是自动检测更新那种 还是只是加个按钮?🫣

**Comment by TCOTC** [comment]
自动检测的那种

**Comment by zxkmm** [comment]
这个我不太清楚怎么写🫣 

原则上应该可以请求比对一下 https://update.greasyfork.org/scripts/503258/%E5%B1%8F%E8%94%BD%E6%8C%87%E5%AE%9A%E7%94%A8%E6%88%B7%E5%B8%96%E5%AD%90.user.js 这个里面的@version和本体上的（新加一个version变量，因为js没有macro）

但是有跨站请求保护这个东西，不知道要怎么请求

**Comment by zxkmm** [comment]
然后violent monkey好像自动从greasyfork检查更新的功能
![image](https://github.com/user-attachments/assets/f561acd4-695d-4bda-992f-8bc0d18b1440)

**Comment by zxkmm** [comment]
测了一下，更新应该是是正常工作的
![image](https://github.com/user-attachments/assets/1daed0dd-7d6f-4646-8e1d-512b3cc7a933)

**Comment by TCOTC** [comment]
刚刚更新了 v0.4 ，更新地址有了

![image](https://github.com/user-attachments/assets/e164d8f3-a2fd-47c0-b2ab-8b835f6e12e2)

**Comment by zxkmm** [comment]
哦哦我懂了！好像是这个是greasyfork的发布页面的一个功能🫣🫣🫣

**Comment by TCOTC** [comment]
还缺个：

```
// @homepage    https://github.com/zxkmm/ld246_blacklist
```

**Comment by zxkmm** [comment]
谢谢T佬

**Comment by zxkmm** [comment]
我把T佬设为collabrator了，有空的话辛苦直接push，感谢🫣
