### ISSUE TITLE
页面划到底之后新加载出来的条目无法屏蔽

### ISSUE THREAD

**Issue by TCOTC** [zxkmm/ld246_blacklist#5]

**Comment by zxkmm** [comment]
目前的实现是加载后每tick1秒，一共10tick来屏蔽，因为我不会写这种动态加载的监听器。但是至于你说的划到底，新加载条目的功能我这边似乎是没有复现，我这边划到底就没了，是不是其他浏览器插件提供的呢？

**Comment by TCOTC** [comment]
这个网址：https://ld246.com/recent/reply

**Comment by zxkmm** [comment]
谢谢，现在看到划到底的功能了（只是主页没有）。不过这个我有点不会写🫣等我问问gpt，但估计gpt也给不出合理的方案🫣

**Comment by zxkmm** [comment]
实在不行只能死循环轮询了，我感觉目前这个好像性能也没啥折扣

**Comment by zxkmm** [comment]
我去试了下deepseek和chatGPT不出所料AI给的代码错的太离谱了
我先写 ~~称~~ 成轮询了，目前感觉没啥性能问题
如果有的话再想办法
67d74f443014cda1400220418ec053925e9d9c62
